module.exports = [
  {
    "title": "Scaling Up Symbolic Analysis by Removing Z-Equivalent States",
    "date": "2014",
    "authors": [
      "Yueqi Li", "Shing-Chi Cheung", "Xiangyu Zhang", "Yepang Liu"
    ],
    "venue": "ACM Transactions on Software Engineering and Methodology 23(4), August 2014",
    "venueShort": "TOSEM",
    "tags": [],
    "abstract": `
    Path explosion is a major issue in applying path-sensitive symbolic analysis to large programs. We ob- serve that many symbolic states generated by the symbolic analysis of a procedure are indistinguishable to its callers. It is, therefore, possible to keep only one state from each set of equivalent symbolic states without affecting the analysis result. Based on this observation, we propose an equivalence relation called z-equivalence, which is weaker than logical equivalence, to relate a large number of z-equivalent states. We prove that z-equivalence is strong enough to guarantee that paths to be traversed by the symbolic analysis of two z-equivalent states are identical, giving the same solutions to satisfiability and validity queries. We propose a sound linear algorithm to detect z-equivalence. Our experiments show that the symbolic analysis that leverages z-equivalence is able to achieve more than ten orders of magnitude reduction in terms of search space. The reduction significantly alleviates the path explosion problem, enabling us to apply symbolic analysis in large programs such as Hadoop and Linux Kernel.
    `,
    "paperUrl": "http://sccpu2.cse.ust.hk/andrewust/files/tosem14.pdf",
    
    
    "bibtex": `
@article{Li:TOSEM2014,
  author = {Li, Yueqi and Cheung, Shing-Chi and Zhang, Xiangyu and Liu, Yepang},
  title = {Scaling Up Symbolic Analysis by Removing Z-Equivalent States},
  journal = {ACM Trans. Softw. Eng. Methodol.},
  issue_date = {August 2014},
  volume = {23},
  number = {4},
  month = sep,
  year = {2014},
  pages = {34:1--34:32},
  articleno = {34},
  url = {http://doi.acm.org/10.1145/2652484},
}
    `
  }
]